# Animals

Concept.create!(word: "cat", image: "http://i.imgur.com/uGiHlan.jpg", category: "animals")
Concept.create!(word: "dog", image: "http://i.imgur.com/5ZL2iwN.jpg", category: "animals")
Concept.create!(word: "bird", image: "http://i.imgur.com/e8MSj2m.jpg", category: "animals")
Concept.create!(word: "elephant", image: "http://i.imgur.com/jnbLicP.jpg", category: "animals")
Concept.create!(word: "monkey", image: "http://i.imgur.com/JRcTgKz.jpg", category: "animals")
Concept.create!(word: "seal", image: "http://i.imgur.com/NPOdo1K.jpg", category: "animals")
Concept.create!(word: "sea lion", image: "http://i.imgur.com/2Es33lH.jpg", category: "animals")
Concept.create!(word: "racoon", image: "http://i.imgur.com/uEwP6Hr.jpg", category: "animals")

# Notable Writers

Concept.create(word: "Mordecai Richler", image: "http://i.imgur.com/gOca5wc.jpg?1", category: "writers")
Concept.create(word: "Lord Byron", image: "http://i.imgur.com/cPWf9EI.jpg?1", category: "writers")
Concept.create(word: "Langston Hughes", image: "http://i.imgur.com/cXsBC0E.jpg?1", category: "writers")
Concept.create(word: "Jane Austen", image: "http://i.imgur.com/eUBhNzz.jpg?1", category: "writers")
Concept.create(word: "Ernest Hemingway", image: "http://i.imgur.com/szyYyvI.jpg?1", category: "writers")
Concept.create(word: "Emily Bronte", image: "http://i.imgur.com/O1oamH5.jpg?1", category: "writers")
Concept.create(word: "Charlotte Bronte", image: "http://i.imgur.com/G95wcxf.jpg?1", category: "writers")
Concept.create(word: "Margaret Atwood", image: "http://i.imgur.com/g2jgAVD.jpg?1", category: "writers")
Concept.create(word: "Isaac Asimov", image: "http://i.imgur.com/yLqJR4i.jpg?1", category: "writers")
Concept.create(word: "Ursula K. Le Guin", image: "http://i.imgur.com/bWI1n4O.jpg?1", category: "writers")
Concept.create(word: "Gertrude Stein", image: "http://i.imgur.com/X6FPbtx.jpg?1", category: "writers")
Concept.create(word: "William Shakespeare", image: "http://i.imgur.com/WpNPWeP.jpg", category: "writers")
Concept.create(word: "Edgar Allan Poe", image: "http://i.imgur.com/BPPYlO6.jpg?1", category: "writers")
Concept.create(word: "Murakami", image: "http://i.imgur.com/aqRnaop.jpg?1", category: "writers")
Concept.create(word: "Mark Twain", image: "http://i.imgur.com/L7TuRIe.jpg", category: "writers")

# Famous Artworks

Concept.create!(word: "Angel of the North (Antony Gormley)", image: "http://i.imgur.com/ywTp5BF.jpg?1", category: "artworks")
Concept.create!(word: "Creation of Adam (Michelangelo)", image: "http://i.imgur.com/vt1aabQ.jpg?1", category: "artworks")
Concept.create!(word: "The Thinker (Auguste Rodin)", image: "http://i.imgur.com/v1nKHJ5.jpg?1", category: "artworks")
Concept.create!(word: "Great Sphinx of Giza", image: "http://i.imgur.com/TQ39ban.jpg?1", category: "artworks")
Concept.create!(word: "The School of Athens (Raphael)", image: "http://i.imgur.com/NMhEV14.jpg?1", category: "artworks")
Concept.create!(word: "Mona Lisa (Leonardo da Vinci)", image: "http://i.imgur.com/iDug6lO.jpg?1", category: "artworks")
Concept.create!(word: "Moai (Easter Island)", image: "http://i.imgur.com/KwW79IW.jpg?1", category: "artworks")
Concept.create!(word: "The Lady of Shallot (John William Waterhouse)", image: "http://i.imgur.com/pAsw39F.jpg?1", category: "artworks")
Concept.create!(word: "The Kiss (Auguste Rodin)", image: "http://i.imgur.com/D4nl9cv.jpg?1", category: "artworks")
Concept.create!(word: "The Kiss (Gustav Klimt)", image: "http://i.imgur.com/dnFDXjy.jpg?1", category: "artworks")
Concept.create!(word: "David (Michelangelo)", image: "http://i.imgur.com/DCXZVvj.jpg?1", category: "artworks")
Concept.create!(word: "David (Donatello)", image: "http://i.imgur.com/F1VJbkX.jpg?1", category: "artworks")

# Philosophers

Concept.create!(word: "Ludwig Wittgenstein", image: "http://i.imgur.com/R1yB4aZ.png", category: "philosophers")
Concept.create!(word: "Alain Locke", image: "http://i.imgur.com/aTpjXTT.jpg?2", category: "philosophers")
Concept.create!(word: "Angela Davis", image: "http://i.imgur.com/A4fp5cO.jpg?1", category: "philosophers")
Concept.create!(word: "Hannah Arendt", image: "http://i.imgur.com/7pCMF4L.jpg?1", category: "philosophers")
Concept.create!(word: "C.L.R. James", image: "http://i.imgur.com/ZqwChoY.jpg?1", category: "philosophers")
Concept.create!(word: "Confucius", image: "http://i.imgur.com/5qNobw6.jpg?1", category: "philosophers")
Concept.create!(word: "Deepak Chopra", image: "http://i.imgur.com/iN9UuCN.jpg?1", category: "philosophers")
Concept.create!(word: "Jacques Derrida", image: "http://i.imgur.com/RoWVaiE.jpg?1", category: "philosophers")
Concept.create!(word: "Michel Foucault", image: "http://i.imgur.com/5sYstjp.jpg?1", category: "philosophers")
Concept.create!(word: "Jean Luc Godard", image: "http://i.imgur.com/6aPtC5C.jpg?1", category: "philosophers")
Concept.create!(word: "Desmond Hume", image: "http://i.imgur.com/ZJTYKq1.jpg?1", category: "philosophers")
Concept.create!(word: "Jaegwon Kim", image: "http://i.imgur.com/uy0gMHf.jpg?1", category: "philosophers")
Concept.create!(word: "Jean Paul Sartre", image: "http://i.imgur.com/Oqt2Qk8.jpg?1", category: "philosophers")
Concept.create!(word: "John Stuart Mill", image: "http://i.imgur.com/lEAQNaL.jpg?1", category: "philosophers")
Concept.create!(word: "Judith Butler", image: "http://i.imgur.com/Q66mAAH.jpg?1", category: "philosophers")
Concept.create!(word: "Immanuel Kant", image: "http://i.imgur.com/IezznrK.jpg?1", category: "philosophers")
Concept.create!(word: "Gottfried Willhelm Leibniz", image: "http://i.imgur.com/4JoXczc.jpg?1", category: "philosophers")
Concept.create!(word: "Martha Nussbaum", image: "http://i.imgur.com/E2ST2eP.jpg?1", category: "philosophers")
Concept.create!(word: "Willard Van Orman Quine", image: "http://i.imgur.com/oJTjJ2Y.jpg?1", category: "philosophers")
Concept.create!(word: "Ayn Rand", image: "http://i.imgur.com/vaP6Rv2.jpg?1", category: "philosophers")
Concept.create!(word: "Bertrand Russell", image: "http://i.imgur.com/3q1g8q8.jpg?1", category: "philosophers")
Concept.create!(word: "Simone de Beauvoir", image: "http://i.imgur.com/jIx8fEz.jpg?1", category: "philosophers")